-- ============================================================================
-- Sahali — seed Tunisia municipalities + 20 demo field_agent accounts
-- Run this in the Supabase SQL editor (Project → SQL Editor → New query).
--
-- Safe to run on production: every insert is additive-only, guarded by a
-- "does this already exist" check, so re-running this whole script a
-- second time is a harmless no-op — it will never create duplicates and
-- never touches/removes any existing row.
--
-- IMPORTANT: the field_agent section generates a random password PER AGENT
-- and shows them ONCE in the query results at the bottom. Only the bcrypt
-- hash is stored in the database — if you don't copy the passwords from
-- the results grid right after running this, they cannot be recovered and
-- you'll need to reset them via the app instead.
--
-- Data source for municipalities: Wikipedia "List of cities in Tunisia"
-- (fetched 2026-07-08), 335 municipalities across all 24 governorates.
-- The official 2016-reform count is 350, so a handful of the smallest/
-- newest communes may be missing — spot-check against an official INS/
-- ministry source if you need this to be legally authoritative.
-- ============================================================================


-- ── 1. Municipalities ─────────────────────────────────────────────────────

INSERT INTO municipalities (name)
SELECT v.name FROM (VALUES
  ('Tunis'),
  ('Le Bardo'),
  ('Le Kram'),
  ('La Goulette'),
  ('Carthage'),
  ('Sidi Bou Said'),
  ('La Marsa'),
  ('Sidi Hassine'),
  ('Ariana'),
  ('La Soukra'),
  ('Raoued'),
  ('Kalâat el-Andalous'),
  ('Sidi Thabet'),
  ('Ettadhamen'),
  ('Mnihla'),
  ('Ben Arous'),
  ('El Mourouj'),
  ('Hammam Lif'),
  ('Hammam Chott'),
  ('Bou Mhel el-Bassatine'),
  ('Ezzahra'),
  ('Radès'),
  ('Mégrine'),
  ('Mohamedia'),
  ('Mornag'),
  ('Khalidia'),
  ('Fouchana'),
  ('Naassen'),
  ('Manouba'),
  ('Den Den'),
  ('Douar Hicher'),
  ('Oued Ellil'),
  ('Mornaguia'),
  ('Borj El Amri'),
  ('Djedeida'),
  ('Tebourba'),
  ('El Battan'),
  ('Nabeul'),
  ('Dar Châabane El Fehri'),
  ('Béni Khiar'),
  ('El Maâmoura'),
  ('Somâa'),
  ('Korba'),
  ('Tazarka'),
  ('Menzel Temime'),
  ('Menzel Horr'),
  ('El Mida'),
  ('Kelibia'),
  ('Azmour'),
  ('Hammam Ghezèze'),
  ('Dar Allouch'),
  ('El Haouaria'),
  ('Takelsa'),
  ('Soliman'),
  ('Korbous'),
  ('Menzel Bouzelfa'),
  ('Béni Khalled'),
  ('Zaouiet Djedidi'),
  ('Grombalia'),
  ('Bou Argoub'),
  ('Hammamet'),
  ('Fondouk Jedid'),
  ('Chrifet'),
  ('Sidi Djedidi'),
  ('Tazougrane'),
  ('Zaghouan'),
  ('Zriba'),
  ('Bir Mcherga'),
  ('Djebel Oust'),
  ('El Fahs'),
  ('Nadhour'),
  ('El Amaiem'),
  ('Saouaf'),
  ('Bizerte'),
  ('Sejnane'),
  ('Mateur'),
  ('Menzel Bourguiba'),
  ('Tinja'),
  ('Ghar al Milh'),
  ('Aousja'),
  ('Menzel Jemil'),
  ('Menzel Abderrahmane'),
  ('El Alia'),
  ('Ras Jebel'),
  ('Metline'),
  ('Raf Raf'),
  ('El Hachachna'),
  ('Ghezala'),
  ('Joumine'),
  ('Utique'),
  ('Béja'),
  ('El Maâgoula'),
  ('Zahret Medien'),
  ('Nefza'),
  ('Téboursouk'),
  ('Testour'),
  ('Goubellat'),
  ('Medjez El Bab'),
  ('Ouchtata'),
  ('Sidi Ismaïl'),
  ('Slouguia'),
  ('Thibar'),
  ('Jendouba'),
  ('Bou Salem'),
  ('Tabarka'),
  ('Aïn Draham'),
  ('Fernana'),
  ('Beni M''Tir'),
  ('Ghardimaou'),
  ('Oued Melliz'),
  ('Jouaouda'),
  ('Souk Sebt'),
  ('Kalaa'),
  ('Khmairia'),
  ('Aïn Sobh'),
  ('Balta'),
  ('El Kef'),
  ('Nebeur'),
  ('Touiref'),
  ('Sakiet Sidi Youssef'),
  ('Tajerouine'),
  ('Menzel Salem'),
  ('Kalaat Senan'),
  ('Kalâat Khasba'),
  ('Jérissa'),
  ('El Ksour'),
  ('Dahmani'),
  ('Sers'),
  ('Bahra'),
  ('El Marja'),
  ('Zaafrane'),
  ('Siliana'),
  ('Bou Arada'),
  ('Gaâfour'),
  ('El Krib'),
  ('Sidi Bou Rouis'),
  ('Maktar'),
  ('Rouhia'),
  ('Kesra'),
  ('Bargou'),
  ('El Aroussa'),
  ('El Hababsa'),
  ('Sidi Morched'),
  ('Sousse'),
  ('Ksibet Thrayet'),
  ('Ezzouhour'),
  ('Zaouiet Sousse'),
  ('Hammam Sousse'),
  ('Akouda'),
  ('Kalâa Kebira'),
  ('Sidi Bou Ali'),
  ('Hergla'),
  ('Enfidha'),
  ('Bouficha'),
  ('Sidi El Hani'),
  ('M''saken'),
  ('Kalâa Seghira'),
  ('Messaadine'),
  ('Kondar'),
  ('Chott Meriem'),
  ('Grimet'),
  ('Monastir'),
  ('Khniss'),
  ('Ouerdanine'),
  ('Sahline'),
  ('Sidi Ameur'),
  ('Zéramdine'),
  ('Beni Hassen'),
  ('Ghenada'),
  ('Jemmal'),
  ('Menzel Kamel'),
  ('Zaouiet Kontoch'),
  ('Bembla'),
  ('Menzel Ennour'),
  ('El Masdour'),
  ('Moknine'),
  ('Sidi Bennour'),
  ('Menzel Fersi'),
  ('Amiret El Fhoul'),
  ('Amiret Touazra'),
  ('Amiret Hajjaj'),
  ('Cherahil'),
  ('Bekalta'),
  ('Téboulba'),
  ('Ksar Hellal'),
  ('Ksibet El Mediouni'),
  ('Bennane Bodheur'),
  ('Touza'),
  ('Sayada'),
  ('Lemta'),
  ('Bouhjar'),
  ('Menzel Hayet'),
  ('Mahdia'),
  ('Rejiche'),
  ('Bou Merdes'),
  ('Ouled Chamekh'),
  ('Chorbane'),
  ('Hebira'),
  ('Essouassi'),
  ('El Djem'),
  ('Kerker'),
  ('Chebba'),
  ('Melloulèche'),
  ('Sidi Alouane'),
  ('Ksour Essef'),
  ('El Bradâa'),
  ('El Hekaima'),
  ('Sidi Zid'),
  ('Tlelsa'),
  ('Zelba'),
  ('Sfax'),
  ('Sakiet Ezzit'),
  ('Chihia'),
  ('Sakiet Eddaïer'),
  ('Gremda'),
  ('El Aïn'),
  ('Thyna'),
  ('Agareb'),
  ('Jebiniana'),
  ('El Hencha'),
  ('Menzel Chaker'),
  ('Ghraïba'),
  ('Bir Ali Ben Khalifa'),
  ('Skhira'),
  ('Mahares'),
  ('Kerkennah'),
  ('El Achech'),
  ('El Amra'),
  ('El Nasr'),
  ('Hadjeb'),
  ('Hazeg'),
  ('Ouabed'),
  ('Kairouan'),
  ('Chebika'),
  ('Sbikha'),
  ('Oueslatia'),
  ('Aïn Djeloula'),
  ('Haffouz'),
  ('El Alâa'),
  ('Hajeb El Ayoun'),
  ('Nasrallah'),
  ('Menzel Mehiri'),
  ('Echrarda'),
  ('Bou Hajla'),
  ('Raqqada'),
  ('Chraitia'),
  ('Sisseb'),
  ('Jehina'),
  ('Aïn El Beïdha'),
  ('Chaouachi'),
  ('Abida'),
  ('Kasserine'),
  ('Sbeitla'),
  ('Sbiba'),
  ('Jedelienne'),
  ('Thala'),
  ('Haïdra'),
  ('Foussana'),
  ('Fériana'),
  ('Thélepte'),
  ('Magel Bel Abbès'),
  ('Sidi Bouzid'),
  ('Jilma'),
  ('Cebbala Ouled Asker'),
  ('Bir El Hafey'),
  ('Sidi Ali Ben Aoun'),
  ('Menzel Bouzaiane'),
  ('Meknassy'),
  ('Mezzouna'),
  ('Regueb'),
  ('Ouled Haffouz'),
  ('Souk Jedid'),
  ('Sidi Bouzid Ouest'),
  ('Sidi Bouzid Est'),
  ('El Hichria'),
  ('Baten Ghzal'),
  ('Gabès'),
  ('Chenini Nahal'),
  ('Ghannouch'),
  ('Métouia'),
  ('Oudhref'),
  ('El Hamma'),
  ('Matmata'),
  ('Nouvelle Matmata'),
  ('Mareth'),
  ('Zarat'),
  ('Teboulbou'),
  ('Habib Thameur Bouatouch'),
  ('Kettana'),
  ('Bouchemma'),
  ('Dkhilet Toujane'),
  ('Menzel El Habib'),
  ('Medenine'),
  ('Beni Khedache'),
  ('Ben Gardane'),
  ('Zarzis'),
  ('Houmt Souk'),
  ('Midoun'),
  ('Ajim'),
  ('Sidi Makhlouf'),
  ('Tataouine'),
  ('Bir Lahmar'),
  ('Ghomrassen'),
  ('Dehiba'),
  ('Remada'),
  ('Smâr'),
  ('Gafsa'),
  ('El Ksar'),
  ('Moularès'),
  ('Redeyef'),
  ('Métlaoui'),
  ('Mdhila'),
  ('El Guettar'),
  ('Sened'),
  ('Belkhir'),
  ('Lalla'),
  ('Sidi Aïch'),
  ('Sidi Boubaker'),
  ('Zannouch'),
  ('Tozeur'),
  ('Degache'),
  ('El Hamma du Jérid'),
  ('Nafta'),
  ('Tamerza'),
  ('Hazoua'),
  ('Kebili'),
  ('Djemna'),
  ('Douz'),
  ('El Golâa'),
  ('Souk Lahad'),
  ('Bechli'),
  ('Bechri'),
  ('Faouar'),
  ('Rjim Maatoug')
) AS v(name)
WHERE NOT EXISTS (SELECT 1 FROM municipalities m WHERE m.name = v.name);


-- ── 2. Demo field_agent accounts ─────────────────────────────────────────
-- pgcrypto gives us crypt()/gen_salt('bf') for bcrypt hashes compatible
-- with the backend's passlib bcrypt verifier, and gen_random_bytes() for
-- per-agent random passwords. gen_random_uuid() is built into Postgres
-- core (13+), no extension needed for that part.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH new_agents (full_name, email, municipality_name) AS (
  VALUES
    ('Agent Tunis',       'agent.tunis@sahali.tn',       'Tunis'),
    ('Agent Sfax',        'agent.sfax@sahali.tn',        'Sfax'),
    ('Agent Sousse',      'agent.sousse@sahali.tn',      'Sousse'),
    ('Agent Bizerte',     'agent.bizerte@sahali.tn',     'Bizerte'),
    ('Agent Ariana',      'agent.ariana@sahali.tn',      'Ariana'),
    ('Agent Ben Arous',   'agent.benarous@sahali.tn',    'Ben Arous'),
    ('Agent Nabeul',      'agent.nabeul@sahali.tn',      'Nabeul'),
    ('Agent Kairouan',    'agent.kairouan@sahali.tn',    'Kairouan'),
    ('Agent Gabès',       'agent.gabes@sahali.tn',       'Gabès'),
    ('Agent Gafsa',       'agent.gafsa@sahali.tn',       'Gafsa'),
    ('Agent Médenine',    'agent.medenine@sahali.tn',    'Medenine'),
    ('Agent Monastir',    'agent.monastir@sahali.tn',    'Monastir'),
    ('Agent Mahdia',      'agent.mahdia@sahali.tn',      'Mahdia'),
    ('Agent Kasserine',   'agent.kasserine@sahali.tn',   'Kasserine'),
    ('Agent Sidi Bouzid', 'agent.sidibouzid@sahali.tn',  'Sidi Bouzid'),
    ('Agent Jendouba',    'agent.jendouba@sahali.tn',    'Jendouba'),
    ('Agent Le Kef',      'agent.lekef@sahali.tn',       'El Kef'),
    ('Agent Siliana',     'agent.siliana@sahali.tn',     'Siliana'),
    ('Agent Zaghouan',    'agent.zaghouan@sahali.tn',    'Zaghouan'),
    ('Agent Tataouine',   'agent.tataouine@sahali.tn',   'Tataouine')
),
prepared AS (
  SELECT
    na.full_name,
    na.email,
    m.id AS municipality_id,
    -- 12-char random password, unique per agent
    substr(encode(gen_random_bytes(9), 'base64'), 1, 12) AS plain_password
  FROM new_agents na
  JOIN municipalities m ON m.name = na.municipality_name
  WHERE NOT EXISTS (SELECT 1 FROM users u WHERE u.email = na.email)
),
inserted AS (
  INSERT INTO users (id, role, full_name, email, password_hash, municipality_id)
  SELECT
    gen_random_uuid(),
    'field_agent',
    full_name,
    email,
    crypt(plain_password, gen_salt('bf', 12)),
    municipality_id
  FROM prepared
  RETURNING email
)
-- ── COPY THIS RESULT NOW — passwords are never stored, only the hash is. ──
SELECT p.email, p.plain_password AS password
FROM prepared p
JOIN inserted i ON i.email = p.email;
