import { createContext, useContext, useState, useEffect, type ReactNode } from 'react'

type Lang = 'fr' | 'ar'

const FR = {
  // Navigation
  nav_dashboard:     'Tableau de bord',
  nav_map:           'Carte en direct',
  nav_reports:       'Signalements',
  nav_interventions: 'Interventions',
  nav_calendar:      'Calendrier',
  nav_teams:         'Équipes & Agents',
  nav_municipalities:'Municipalités',
  nav_categories:    'Catégories',
  nav_statistics:    'Statistiques',
  nav_settings:      'Paramètres',
  // Status (badge labels)
  status_submitted:   'Nouveau',
  status_received:    'Reçu',
  status_under_review:'En examen',
  status_in_progress: 'En cours',
  status_resolved:    'Résolu',
  status_rejected:    'Rejeté',
  // Priority
  priority_low:      'Basse',
  priority_medium:   'Moyenne',
  priority_high:     'Haute',
  priority_critical: 'Critique',
  // Roles
  role_admin:        'Administrateur',
  role_supervisor:   'Superviseur',
  role_analyst:      'Analyste',
  role_field_agent:  'Agent terrain',
  role_citizen:      'Citoyen',
  // Agent status
  agent_active:      'Actif',
  agent_inactive:    'Inactif',
  // Language toggle
  lang_fr:           'Français',
  lang_ar:           'العربية',
  // Sidebar footer
  sidebar_admin:     'Administration',
  sidebar_city:      'La Marsa',
  // Page subtitles (static)
  sub_map:           'Visualisation en temps réel des signalements actifs.',
  sub_reports:       'Gestion et suivi de tous les signalements citoyens.',
  sub_interventions: 'Gestion et planification des équipes de terrain.',
  sub_calendar:      'Planning des interventions programmées.',
  sub_teams:         'Gestion des agents et équipes municipales.',
  sub_municipalities:"Vue d'ensemble des municipalités partenaires.",
  sub_categories:    'Configuration des catégories de signalements.',
  sub_statistics:    'Analyse des performances et indicateurs clés.',
  sub_settings:      'Configuration de la plateforme municipale.',
  // TopBar
  topbar_search:     'Rechercher un signalement, agent...',
  notif_title:       'Notifications',
  notif_empty:       'Aucune notification',
  notif_view:        'Voir le signalement →',
  btn_logout:        'Se déconnecter',
  // Dashboard
  dash_export:       'Exporter',
  kpi_total:         'Total signalements',
  kpi_today:         "aujourd'hui",
  kpi_new:           'nouveaux',
  kpi_pending:       'En attente',
  kpi_avg_res:       'Résolution moy.:',
  kpi_resolved:      'Résolus',
  kpi_rejected_lbl:  'Rejetés',
  dist_title:        'Répartition des statuts',
  dist_subtitle:     'Distribution actuelle de tous les signalements',
  dist_donut:        'Répartition',
  dist_total:        'Total',
  dist_submitted:    'Soumis',
  dist_in_progress:  'En cours',
  dist_resolved:     'Résolus',
  dist_rejected:     'Rejetés',
  rate_title:        'Taux de résolution',
  rate_target:       'Objectif: 85%',
  rate_excellent:    'Performance excellente',
  rate_below:        "En dessous de l'objectif",
  avg_time_title:    'Temps de résolution moyen',
  avg_time_per:      'par signalement résolu',
  recent_title:      'Signalements récents',
  see_all:           'Voir tout',
  // Statistics
  stats_subtitle:       'Tableau de bord analytique — données en temps réel',
  stat_submitted:       'Soumis',
  stats_kpi_rate:       'Taux de résolution',
  stats_kpi_active:     'En cours de traitement',
  stats_kpi_active_sub: 'Interventions actives',
  stats_kpi_avg:        'Résolution moyenne',
  stats_kpi_avg_sub:    'Délai moyen observé',
  chart_by_status:      'Répartition par statut',
  stats_overview:       "Vue d'ensemble",
  stats_resolved_pct:   'résolus',
  stats_to_treat:       'À traiter',
  stats_detail:         'Détail par statut',
  col_reports_count:    'Signalements',
  col_share_pct:        'Part (%)',
  col_indicator:        'Indicateur',
  // Teams
  teams_title:          'Équipes & Agents',
  staff_members:        'membres du personnel',
  btn_add_agent:        'Ajouter un agent',
  stat_assigned:        'Assignés',
  stat_resolved_n:      'Résolus',
  stat_in_prog:         'En cours',
  performance:          'Performance',
  col_agent:            'Agent',
  col_role:             'Rôle',
  col_actions:          'Actions',
  btn_deactivate:       'Désactiver',
  btn_activate:         'Activer',
  btn_deactivate_account: 'Désactiver le compte',
  btn_activate_account:   'Réactiver le compte',
  updating:             'Mise à jour...',
  panel_agent:          'Fiche agent',
  missions_active:      'Missions actives',
  missions_none:        'Aucune mission en cours',
  member_since:         'Membre depuis',
  modal_add_title:      'Ajouter un agent',
  modal_add_sub:        'Créer un nouveau compte membre du personnel',
  lbl_full_name:        'Nom complet *',
  lbl_email_f:          'Email *',
  lbl_phone_f:          'Téléphone',
  lbl_role_f:           'Rôle *',
  lbl_municipality_f:   'Municipalité *',
  lbl_password_f:       'Mot de passe *',
  btn_create_account:   'Créer le compte',
  creating:             'Création...',
  required_fields_err:  'Tous les champs obligatoires doivent être remplis.',
  select_option:        'Sélectionner...',
  ph_password_min:      'Min. 8 caractères',
  err_creation:         'Erreur lors de la création',
  // Interventions
  int_reception:        'Réception',
  int_terminated:       'Terminés',
  int_detail:           'Détail intervention',
  int_final_state:      'Ce signalement est dans un état final.',
  note_optional_int:    'Note optionnelle (commentaire interne)...',
  // Calendar
  day_mon:              'Lun',
  day_tue:              'Mar',
  day_wed:              'Mer',
  day_thu:              'Jeu',
  day_fri:              'Ven',
  day_sat:              'Sam',
  day_sun:              'Dim',
  week_today:           "Aujourd'hui",
  cal_loading:          'Chargement des événements...',
  cal_under_review:     'En examen',
  cal_in_progress:      'En cours',
  cal_done_week:        'Terminés cette semaine',
  cal_total:            'Total à suivre',
  // Settings
  settings_sub:         'Configuration de votre compte et de la plateforme.',
  section_profile:      'Mon profil',
  section_notif:        'Notifications',
  section_sla:          'Seuils SLA',
  section_security:     'Sécurité',
  section_integ:        'Intégrations',
  personal_info:        'Informations personnelles',
  lbl_full_name_s:      'Nom complet',
  lbl_email_s:          'Adresse e-mail',
  lbl_phone_s:          'Téléphone',
  lbl_pref_lang:        'Langue préférée',
  member_since_s:       'Membre depuis',
  notif_channels:       'Canaux de notification',
  notif_push_lbl:       'Notifications push',
  notif_push_desc:      'Via Firebase Cloud Messaging (FCM)',
  notif_sms_lbl:        'SMS',
  notif_sms_desc:       'Via Twilio ou opérateur local tunisien',
  notif_email_lbl:      'Email',
  notif_email_desc:     'Via SendGrid ou SMTP',
  notif_sla_lbl:        'Alertes SLA',
  notif_sla_desc:       'Notification si délai SLA dépassé',
  sla_config_title:     'Configuration des SLA',
  sla_config_desc:      'Délais cibles de résolution par catégorie de signalement.',
  sla_hours:            'heures',
  under_dev:            'en cours de développement',
  btn_cancel_s:         'Annuler',
  btn_save_s:           'Enregistrer les modifications',
  // Municipalities
  muni_registered:      'municipalités enregistrées',
  muni_total_reports:   'Signalements totaux',
  muni_avg_resolution:  'Taux de résolution moyen',
  muni_field_agents:    'Agents terrain',
  col_muni:             'Municipalité',
  col_subscription:     'Abonnement',
  col_open_reports:     'Ouverts',
  col_agents_m:         'Agents',
  col_rate:             'Taux',
  muni_detail:          'Détails',
  muni_detail_rate:     'Taux de résolution',
  // Reports page
  reports_title:        'Signalements',
  reports_export:       'Exporter CSV',
  reports_search:       'Rechercher par code, titre, ville...',
  reports_all_statuses: 'Tous les statuts',
  col_code:   'Code',
  col_title:  'Titre',
  col_city:   'Ville',
  col_priority:'Priorité',
  col_status: 'Statut',
  col_date:   'Date',
  no_reports: 'Aucun signalement trouvé',
  prev:       '← Précédent',
  next:       'Suivant →',
  // Detail tabs
  tab_info:        'Détail',
  tab_history:     'Traçabilité',
  tab_assignment:  'Assignation',
  tab_report:      'Rapport',
  // Detail
  lbl_category:    'Catégorie',
  lbl_address:     'Adresse',
  lbl_description: 'Description',
  lbl_submitted:   'Soumis le',
  lbl_resolved_on: 'Résolu le',
  change_status:   'Changer le statut',
  move_to:         'Passer à',
  note_optional:   'Note (optionnel)',
  rejection_reason:'Motif de rejet *',
  rejection_placeholder: 'Expliquez la raison du rejet...',
  btn_confirm:     'Confirmer',
  btn_cancel:      'Annuler',
  // History
  status_history:  'Historique des statuts',
  by:              'par',
  no_history:      'Aucun historique',
  // Assignment
  assigned_agents: 'Agents assignés',
  reassign:        'Réassigner',
  assign_agents:   'Assigner des agents',
  assign_note_placeholder: "Note d'assignation (optionnel)",
  btn_assign:      'Assigner',
  assigning:       'Assignation...',
  no_agents:       'Aucun agent disponible',
  assign_history:  "Historique d'assignation",
  assigned_by:     'assigné par',
  // Resolution
  report_locked:   'Disponible une fois le signalement résolu',
  resolved_by:     'Résolu par',
  intervention_report: "Rapport d'intervention",
  materials_used:  'Matériaux utilisés',
  team:            'Équipe',
  create_report:   'Créer le rapport de résolution',
  report_comment_label: "Compte-rendu d'intervention *",
  report_comment_placeholder: 'Décrivez les actions réalisées...',
  materials_label: 'Matériaux utilisés',
  materials_placeholder: 'Ex: 2 m³ de béton, signalétique...',
  btn_create_report: 'Créer le rapport',
  saving:          'Enregistrement...',
  // Map
  map_title:       'Carte',
  map_subtitle:    'signalements géolocalisés',
  map_all_statuses:'Tous les statuts',
  map_summary:     'Résumé',
  map_total:       'Total',
  map_today:       "Aujourd'hui",
  map_displayed:   'Affichés',
  map_avg:         'Moy. résolution',
  map_by_status:   'Par statut',
  // Categories
  categories_title: 'Catégories',
  categories_configured: 'catégories configurées',
  root_categories: 'Catégories racines',
  sub_categories:  'Sous-catégorie',
  root_category:   'Catégorie racine',
  priority_label:  'Priorité',
  sla_target:      'SLA cible',
  // Common
  loading:         'Chargement...',
  refresh:         'Actualiser',
  error_retry:     'Réessayer',
}

const AR: typeof FR = {
  nav_dashboard:     'لوحة القيادة',
  nav_map:           'الخريطة المباشرة',
  nav_reports:       'التقارير',
  nav_interventions: 'التدخلات',
  nav_calendar:      'التقويم',
  nav_teams:         'الفرق والعملاء',
  nav_municipalities:'البلديات',
  nav_categories:    'الفئات',
  nav_statistics:    'الإحصائيات',
  nav_settings:      'الإعدادات',
  status_submitted:   'جديد',
  status_received:    'مستلم',
  status_under_review:'قيد الدراسة',
  status_in_progress: 'قيد التنفيذ',
  status_resolved:    'محلول',
  status_rejected:    'مرفوض',
  priority_low:      'منخفضة',
  priority_medium:   'متوسطة',
  priority_high:     'عالية',
  priority_critical: 'حرجة',
  role_admin:        'مدير',
  role_supervisor:   'مشرف',
  role_analyst:      'محلل',
  role_field_agent:  'عميل ميداني',
  role_citizen:      'مواطن',
  agent_active:      'نشط',
  agent_inactive:    'غير نشط',
  lang_fr:           'Français',
  lang_ar:           'العربية',
  sidebar_admin:     'الإدارة',
  sidebar_city:      'المرسى',
  sub_map:           'عرض البلاغات النشطة في الوقت الفعلي.',
  sub_reports:       'إدارة ومتابعة جميع البلاغات المدنية.',
  sub_interventions: 'إدارة وتخطيط فرق الميدان.',
  sub_calendar:      'جدول التدخلات المبرمجة.',
  sub_teams:         'إدارة العملاء والفرق البلدية.',
  sub_municipalities:'نظرة عامة على البلديات الشريكة.',
  sub_categories:    'إعداد فئات البلاغات.',
  sub_statistics:    'تحليل الأداء والمؤشرات الرئيسية.',
  sub_settings:      'إعدادات المنصة البلدية.',
  topbar_search:     'بحث عن بلاغ، عميل...',
  notif_title:       'الإشعارات',
  notif_empty:       'لا توجد إشعارات',
  notif_view:        '← عرض البلاغ',
  btn_logout:        'تسجيل الخروج',
  dash_export:       'تصدير',
  kpi_total:         'إجمالي البلاغات',
  kpi_today:         'اليوم',
  kpi_new:           'جديدة',
  kpi_pending:       'قيد الانتظار',
  kpi_avg_res:       'متوسط الحل:',
  kpi_resolved:      'محلولة',
  kpi_rejected_lbl:  'مرفوضة',
  dist_title:        'توزيع الحالات',
  dist_subtitle:     'التوزيع الحالي لجميع البلاغات',
  dist_donut:        'التوزيع',
  dist_total:        'الإجمالي',
  dist_submitted:    'مقدم',
  dist_in_progress:  'قيد التنفيذ',
  dist_resolved:     'محلولة',
  dist_rejected:     'مرفوضة',
  rate_title:        'معدل الحل',
  rate_target:       'الهدف: 85%',
  rate_excellent:    'أداء ممتاز',
  rate_below:        'أقل من الهدف',
  avg_time_title:    'متوسط وقت الحل',
  avg_time_per:      'لكل بلاغ محلول',
  recent_title:      'البلاغات الأخيرة',
  see_all:           'عرض الكل',
  stats_subtitle:       'لوحة تحليلية — بيانات في الوقت الفعلي',
  stat_submitted:       'مقدم',
  stats_kpi_rate:       'معدل الحل',
  stats_kpi_active:     'قيد المعالجة',
  stats_kpi_active_sub: 'تدخلات نشطة',
  stats_kpi_avg:        'متوسط الحل',
  stats_kpi_avg_sub:    'التأخير المتوسط',
  chart_by_status:      'التوزيع حسب الحالة',
  stats_overview:       'نظرة عامة',
  stats_resolved_pct:   'محلول',
  stats_to_treat:       'للمعالجة',
  stats_detail:         'تفاصيل حسب الحالة',
  col_reports_count:    'البلاغات',
  col_share_pct:        'النسبة (%)',
  col_indicator:        'المؤشر',
  teams_title:          'الفرق والعملاء',
  staff_members:        'من أعضاء الفريق',
  btn_add_agent:        'إضافة عميل',
  stat_assigned:        'مكلف',
  stat_resolved_n:      'محلول',
  stat_in_prog:         'جار',
  performance:          'الأداء',
  col_agent:            'العميل',
  col_role:             'الدور',
  col_actions:          'الإجراءات',
  btn_deactivate:       'تعطيل',
  btn_activate:         'تفعيل',
  btn_deactivate_account: 'تعطيل الحساب',
  btn_activate_account:   'إعادة تفعيل الحساب',
  updating:             'جار التحديث...',
  panel_agent:          'ملف العميل',
  missions_active:      'المهام النشطة',
  missions_none:        'لا توجد مهام نشطة',
  member_since:         'عضو منذ',
  modal_add_title:      'إضافة عميل',
  modal_add_sub:        'إنشاء حساب عضو جديد',
  lbl_full_name:        'الاسم الكامل *',
  lbl_email_f:          'البريد الإلكتروني *',
  lbl_phone_f:          'الهاتف',
  lbl_role_f:           'الدور *',
  lbl_municipality_f:   'البلدية *',
  lbl_password_f:       'كلمة المرور *',
  btn_create_account:   'إنشاء الحساب',
  creating:             'جار الإنشاء...',
  required_fields_err:  'يجب ملء جميع الحقول الإلزامية.',
  select_option:        'اختر...',
  ph_password_min:      '8 أحرف على الأقل',
  err_creation:         'خطأ في الإنشاء',
  int_reception:        'الاستقبال',
  int_terminated:       'منتهية',
  int_detail:           'تفاصيل التدخل',
  int_final_state:      'هذا البلاغ في حالة نهائية.',
  note_optional_int:    'ملاحظة اختيارية (تعليق داخلي)...',
  day_mon:              'الاثنين',
  day_tue:              'الثلاثاء',
  day_wed:              'الأربعاء',
  day_thu:              'الخميس',
  day_fri:              'الجمعة',
  day_sat:              'السبت',
  day_sun:              'الأحد',
  week_today:           'اليوم',
  cal_loading:          'جار تحميل الأحداث...',
  cal_under_review:     'قيد الدراسة',
  cal_in_progress:      'قيد التنفيذ',
  cal_done_week:        'منتهية هذا الأسبوع',
  cal_total:            'الإجمالي للمتابعة',
  settings_sub:         'إعدادات حسابك والمنصة.',
  section_profile:      'ملفي الشخصي',
  section_notif:        'الإشعارات',
  section_sla:          'حدود SLA',
  section_security:     'الأمان',
  section_integ:        'التكاملات',
  personal_info:        'المعلومات الشخصية',
  lbl_full_name_s:      'الاسم الكامل',
  lbl_email_s:          'البريد الإلكتروني',
  lbl_phone_s:          'الهاتف',
  lbl_pref_lang:        'اللغة المفضلة',
  member_since_s:       'عضو منذ',
  notif_channels:       'قنوات الإشعارات',
  notif_push_lbl:       'إشعارات الدفع',
  notif_push_desc:      'عبر Firebase Cloud Messaging (FCM)',
  notif_sms_lbl:        'رسائل SMS',
  notif_sms_desc:       'عبر Twilio أو مشغل محلي تونسي',
  notif_email_lbl:      'البريد الإلكتروني',
  notif_email_desc:     'عبر SendGrid أو SMTP',
  notif_sla_lbl:        'تنبيهات SLA',
  notif_sla_desc:       'إشعار عند تجاوز مهلة SLA',
  sla_config_title:     'إعداد SLA',
  sla_config_desc:      'أوقات الحل المستهدفة حسب فئة البلاغ.',
  sla_hours:            'ساعات',
  under_dev:            'قيد التطوير',
  btn_cancel_s:         'إلغاء',
  btn_save_s:           'حفظ التغييرات',
  muni_registered:      'بلديات مسجلة',
  muni_total_reports:   'إجمالي البلاغات',
  muni_avg_resolution:  'متوسط معدل الحل',
  muni_field_agents:    'العملاء الميدانيون',
  col_muni:             'البلدية',
  col_subscription:     'الاشتراك',
  col_open_reports:     'المفتوحة',
  col_agents_m:         'العملاء',
  col_rate:             'المعدل',
  muni_detail:          'التفاصيل',
  muni_detail_rate:     'معدل الحل',
  reports_title:        'التقارير',
  reports_export:       'تصدير CSV',
  reports_search:       'بحث بالرمز، العنوان، المدينة...',
  reports_all_statuses: 'جميع الحالات',
  col_code:   'الرمز',
  col_title:  'العنوان',
  col_city:   'المدينة',
  col_priority:'الأولوية',
  col_status: 'الحالة',
  col_date:   'التاريخ',
  no_reports: 'لا توجد تقارير',
  prev:       '→ السابق',
  next:       'التالي ←',
  tab_info:        'التفاصيل',
  tab_history:     'السجل',
  tab_assignment:  'التكليف',
  tab_report:      'التقرير',
  lbl_category:    'الفئة',
  lbl_address:     'العنوان',
  lbl_description: 'الوصف',
  lbl_submitted:   'تاريخ الإرسال',
  lbl_resolved_on: 'تاريخ الحل',
  change_status:   'تغيير الحالة',
  move_to:         'الانتقال إلى',
  note_optional:   'ملاحظة (اختياري)',
  rejection_reason:'سبب الرفض *',
  rejection_placeholder: 'اشرح سبب رفض هذا البلاغ...',
  btn_confirm:     'تأكيد',
  btn_cancel:      'إلغاء',
  status_history:  'سجل الحالات',
  by:              'بواسطة',
  no_history:      'لا يوجد سجل',
  assigned_agents: 'العملاء المكلفون',
  reassign:        'إعادة التكليف',
  assign_agents:   'تكليف عملاء',
  assign_note_placeholder: 'ملاحظة التكليف (اختياري)',
  btn_assign:      'تكليف',
  assigning:       'جار التكليف...',
  no_agents:       'لا يوجد عملاء',
  assign_history:  'سجل التكليفات',
  assigned_by:     'كُلِّف بواسطة',
  report_locked:   'متاح بعد حل البلاغ',
  resolved_by:     'حُل بواسطة',
  intervention_report: 'تقرير التدخل',
  materials_used:  'المواد المستخدمة',
  team:            'الفريق',
  create_report:   'إنشاء تقرير الحل',
  report_comment_label: 'تقرير التدخل *',
  report_comment_placeholder: 'صف الإجراءات المنفذة...',
  materials_label: 'المواد المستخدمة',
  materials_placeholder: 'مثال: 2 م³ خرسانة، لافتات...',
  btn_create_report: 'إنشاء التقرير',
  saving:          'جار الحفظ...',
  map_title:       'الخريطة',
  map_subtitle:    'بلاغات على الخريطة',
  map_all_statuses:'جميع الحالات',
  map_summary:     'ملخص',
  map_total:       'الإجمالي',
  map_today:       'اليوم',
  map_displayed:   'المعروضة',
  map_avg:         'متوسط الحل',
  map_by_status:   'حسب الحالة',
  categories_title: 'الفئات',
  categories_configured: 'فئات مضبوطة',
  root_categories: 'الفئات الرئيسية',
  sub_categories:  'فئة فرعية',
  root_category:   'فئة رئيسية',
  priority_label:  'الأولوية',
  sla_target:      'هدف SLA',
  loading:         'جار التحميل...',
  refresh:         'تحديث',
  error_retry:     'إعادة المحاولة',
}

const DICT: Record<Lang, typeof FR> = { fr: FR, ar: AR }

export type TranslationKey = keyof typeof FR

interface LangCtx {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: TranslationKey) => string
  dir: 'ltr' | 'rtl'
  locale: string
}

const Ctx = createContext<LangCtx>({
  lang: 'fr', setLang: () => {}, t: k => FR[k], dir: 'ltr', locale: 'fr-FR',
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem('sahali_lang') as Lang) ?? 'fr'
  )

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('sahali_lang', l)
  }

  useEffect(() => {
    document.documentElement.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr')
    document.documentElement.setAttribute('lang', lang)
  }, [lang])

  const t = (key: keyof typeof FR) => DICT[lang][key] ?? DICT.fr[key]
  const dir: 'ltr' | 'rtl' = lang === 'ar' ? 'rtl' : 'ltr'
  const locale = lang === 'ar' ? 'ar-TN' : 'fr-FR'

  return <Ctx.Provider value={{ lang, setLang, t, dir, locale }}>{children}</Ctx.Provider>
}

export function useLang() { return useContext(Ctx) }
